### ISSUE TITLE
Erro ao buscar o cep 02716000 na versão 3.0.4

### ISSUE THREAD

**Issue by ricardosaraiva** [netdragoon/zipcode#10]
Ao tentar buscar o cep 02716000 na versão 3.0.4 do pacote está retornando o seguinte erro:
Return value of Canducci\ZipCode\ZipCode::getZipCodeInfo() must be of the type string, null returned

Porém este é um cep valido para o endereço, fiz um downgrade para  a versão 3.0.3 e funciona
{
    "neighborhood": "Limão",
    "city": "São Paulo",
    "state": "São Paulo",
    "address": "Avenida Inajar de Souza",
    "postalCode": "02716-000",
}

**Comment by fulviocanducci** [comment]
Foi adicionado o `null` nos retornos função alterado nessa nova versão https://github.com/netdragoon/zipcode/releases/tag/v3.0.5
por favor teste e me dê se agora resolveu.
