### ISSUE TITLE
Declaration of ZipCodeRequest::get($url) must be compatible with ZipCodeRequestContract::get(string $url)

### ISSUE THREAD

**Issue by rstriquer** [netdragoon/zipcode#11]
Fiz um composer require com a versão 3.0.5 e o seguinte erro aconteceu:

```Shell
[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                                                                    
  Declaration of Canducci\ZipCode\ZipCodeRequest::get($url): Canducci\ZipCode\ZipCodeResponse must be compatible with Canducci\ZipCode\Contracts\ZipCodeRequestContract::get(string $url): Canducci\ZipCode\ZipCodeResponse  ****
```

PS: Apenas reportando o identificado. Bom trabalho.

**Comment by fulviocanducci** [comment]
> Fiz um composer require com a versão 3.0.5 e o seguinte erro aconteceu:
> 
> ```shell
> [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                                                                    
>   Declaration of Canducci\ZipCode\ZipCodeRequest::get($url): Canducci\ZipCode\ZipCodeResponse must be compatible with Canducci\ZipCode\Contracts\ZipCodeRequestContract::get(string $url): Canducci\ZipCode\ZipCodeResponse  ****
> ```
> 
> PS: Apenas reportando o identificado. Bom trabalho.

* Qual foi o seu procedimento?
* Você está instalando no Laravel e se sim qual versão?
* Você está utilizando em algum código?
* Se utilizou Laravel registrou os Services Provider[ como descrito na documentação](https://github.com/netdragoon/zipcode/blob/master/README.md)

Obrigado pela reportada, mas, eu acabei de instalar e não obtive o mesmo problema!

**Comment by rstriquer** [comment]
Eu estava atualizando um código previamente existente, era um update, o pacote já estava funcionando, então imagino que sim para todas as perguntas. O PHP está na versão 7.2.34-8+ubuntu20.04.1+deb.sury.org+1 e o Laravel 5.0.

**Comment by fulviocanducci** [comment]
> Eu estava atualizando um código previamente existente, era um update, o pacote já estava funcionando, então imagino que sim para todas as perguntas. O PHP está na versão 7.2.34-8+ubuntu20.04.1+deb.sury.org+1 e o Laravel 5.0.

- Como estava atualizando?

Observação: Seguinte eu fiz todos os testes, inclusive pelo PHPUNIT e também verifique a tal incompatibilidade, mas, os métodos estão escritos certos com suas declarações certas também.

- Laravel 5.0 tem problemas no PHP 7 isso é fato talvez seja isso, tem como colar também o erro completo?

**Comment by rstriquer** [comment]
Não tenho como providenciar mais detalhes do que já foi passado (se eu conseguir até adiciono aqui), se não for suficiente recomendo que marque a issue como finalizada (e se conseguir mais detalhes re-abro ela com eles para você).

O que está acontecendo é que essa linha abaixo

https://github.com/netdragoon/zipcode/blob/dd4e5bd49b010519a802421f0d3d45ea448b6048/src/Canducci/ZipCode/ZipCodeRequest.php#L18

Deve ter a mesma assinatura do contrato abaixo

https://github.com/netdragoon/zipcode/blob/dd4e5bd49b010519a802421f0d3d45ea448b6048/src/Canducci/ZipCode/Contracts/ZipCodeRequestContract.php#L13

Quando adicionei a definição de "string" no método get da classe ZipCodeRequest e erro parou de ocorrer e a classe funcionou normalmente.

**Comment by fulviocanducci** [comment]
É o seguinte o método um está com `string` tipando a variável $url e o outro não e por isso do problema, fiz a correção e na versão v3.0.6 já foi solucionado, vou deixar aberto o `issue` e por favor teste e me fala se agora ocorreu tudo certo.

Muito obrigado por contribuir, logo vou lançar a versão para PHP 8
