### ISSUE TITLE
Serviço parou de funcionar

### ISSUE THREAD

**Issue by joaovinicius** [netdragoon/zipcode#6]
`{ "message": "CEP JSON inv\u00e1lido", "exception": "Canducci\\ZipCode\\ZipCodeException", "file": "/var/www/web/vendor/canducci/zipcode/src/Canducci/ZipCode/ZipCodeInfo.php", "line": 29, "trace": [ { "file": "/var/www/web/vendor/canducci/zipcode/src/Canducci/ZipCode/ZipCode.php", "line": 92, "function": "__construct", "class": "Canducci\\ZipCode\\ZipCodeInfo", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php", "line": 239, "function": "find", "class": "Canducci\\ZipCode\\ZipCode", "type": "->" }, { "file": "/var/www/web/app/Modules/PersonAPI/Rules/Address.php", "line": 48, "function": "__callStatic", "class": "Illuminate\\Support\\Facades\\Facade", "type": "::" }, { "file": "/var/www/web/app/Modules/PersonAPI/Rules/Address.php", "line": 28, "function": "getAddressFromService", "class": "App\\Modules\\PersonAPI\\Rules\\Address", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Validation/Validator.php", "line": 572, "function": "passes", "class": "App\\Modules\\PersonAPI\\Rules\\Address", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Validation/Validator.php", "line": 392, "function": "validateUsingCustomRule", "class": "Illuminate\\Validation\\Validator", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Validation/Validator.php", "line": 277, "function": "validateAttribute", "class": "Illuminate\\Validation\\Validator", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Validation/Validator.php", "line": 302, "function": "passes", "class": "Illuminate\\Validation\\Validator", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Validation/Validator.php", "line": 314, "function": "fails", "class": "Illuminate\\Validation\\Validator", "type": "->" }, { "file": "/var/www/web/app/Modules/PersonAPI/Services/PersonService.php", "line": 108, "function": "validate", "class": "Illuminate\\Validation\\Validator", "type": "->" }, { "file": "/var/www/web/app/Modules/PersonAPI/Services/PersonService.php", "line": 79, "function": "validateRequiredFields", "class": "App\\Modules\\PersonAPI\\Services\\PersonService", "type": "->" }, { "file": "/var/www/web/app/Core/Http/Controllers/PersonController.php", "line": 84, "function": "isProfileFulfilled", "class": "App\\Modules\\PersonAPI\\Services\\PersonService", "type": "->" }, { "function": "isProfileFulfilled", "class": "App\\Core\\Http\\Controllers\\PersonController", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Controller.php", "line": 54, "function": "call_user_func_array" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php", "line": 45, "function": "callAction", "class": "Illuminate\\Routing\\Controller", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Route.php", "line": 219, "function": "dispatch", "class": "Illuminate\\Routing\\ControllerDispatcher", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Route.php", "line": 176, "function": "runController", "class": "Illuminate\\Routing\\Route", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 680, "function": "run", "class": "Illuminate\\Routing\\Route", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 30, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Router", "type": "->" }, { "file": "/var/www/web/app/Core/Http/Middleware/Tracking.php", "line": 28, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "handle", "class": "App\\Core\\Http\\Middleware\\Tracking", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/app/Core/Http/Middleware/FullCacheByPass.php", "line": 28, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "handle", "class": "App\\Core\\Http\\Middleware\\FullCacheByPass", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php", "line": 41, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "handle", "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php", "line": 43, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "handle", "class": "Illuminate\\Auth\\Middleware\\Authenticate", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php", "line": 75, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/app/Core/Http/Middleware/VerifyCsrfToken.php", "line": 23, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "handle", "class": "App\\Core\\Http\\Middleware\\VerifyCsrfToken", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php", "line": 49, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "handle", "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php", "line": 56, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "handle", "class": "Illuminate\\Session\\Middleware\\StartSession", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php", "line": 37, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "handle", "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php", "line": 66, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "handle", "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 104, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 682, "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 657, "function": "runRouteWithinStack", "class": "Illuminate\\Routing\\Router", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 623, "function": "runRoute", "class": "Illuminate\\Routing\\Router", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Router.php", "line": 612, "function": "dispatchToRoute", "class": "Illuminate\\Routing\\Router", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 176, "function": "dispatch", "class": "Illuminate\\Routing\\Router", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 30, "function": "Illuminate\\Foundation\\Http\\{closure}", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }, { "file": "/var/www/web/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php", "line": 28, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "function": "handle", "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed", "type": "->" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/try_catch_finally.php", "line": 12, "function": "dd_trace_forward_call" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php", "line": 140, "function": "include" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "dd_trace_callback", "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php", "line": 28, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "function": "handle", "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed", "type": "->" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/try_catch_finally.php", "line": 12, "function": "dd_trace_forward_call" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php", "line": 140, "function": "include" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "dd_trace_callback", "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php", "line": 28, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "function": "handle", "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed", "type": "->" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/try_catch_finally.php", "line": 12, "function": "dd_trace_forward_call" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php", "line": 140, "function": "include" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "dd_trace_callback", "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/fideloper/proxy/src/TrustProxies.php", "line": 57, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "function": "handle", "class": "Fideloper\\Proxy\\TrustProxies", "type": "->" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/try_catch_finally.php", "line": 12, "function": "dd_trace_forward_call" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php", "line": 140, "function": "include" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "dd_trace_callback", "class": "Fideloper\\Proxy\\TrustProxies", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php", "line": 21, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest", "type": "->" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/try_catch_finally.php", "line": 12, "function": "dd_trace_forward_call" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php", "line": 140, "function": "include" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "dd_trace_callback", "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php", "line": 21, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest", "type": "->" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/try_catch_finally.php", "line": 12, "function": "dd_trace_forward_call" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php", "line": 140, "function": "include" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "dd_trace_callback", "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php", "line": 27, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize", "type": "->" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/try_catch_finally.php", "line": 12, "function": "dd_trace_forward_call" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php", "line": 140, "function": "include" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "dd_trace_callback", "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php", "line": 62, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "function": "handle", "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode", "type": "->" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/try_catch_finally.php", "line": 12, "function": "dd_trace_forward_call" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php", "line": 140, "function": "include" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 163, "function": "dd_trace_callback", "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", "line": 53, "function": "Illuminate\\Pipeline\\{closure}", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", "line": 104, "function": "Illuminate\\Routing\\{closure}", "class": "Illuminate\\Routing\\Pipeline", "type": "->" }, { "function": "then", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php", "line": 145, "function": "dd_trace_forward_call" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 151, "function": "dd_trace_callback", "class": "Illuminate\\Pipeline\\Pipeline", "type": "->" }, { "file": "/var/www/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 116, "function": "sendRequestThroughRouter", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }, { "file": "/var/www/web/public/index.php", "line": 53, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" } ]}`

**Comment by augustoandrade** [comment]
A ViaCEP removeu o campo "unidade" no Json de retorno deles, removendo ele da validação volta a funcionar.
Vou abrir uma PR pra correção disso.

**Comment by fulviocanducci** [comment]
@joaovinicius e @augustoandrade estou verificando e já estou fazendo a correção, muito obrigado!

**Comment by fulviocanducci** [comment]
@joaovinicius e @augustoandrade foi solucionado versão 3.0.4 com alguns modificações principalmente na parte de cache!

Se por acaso quiserem usar um que é sem cache que foi eu mesmo quem fez: https://packagist.org/packages/canducci/cep

Obrigado
