### ISSUE TITLE
Erro ao pesquisar cep inválido

### ISSUE THREAD

**Issue by developerdelphi** [netdragoon/zipcode#7]
Estou usanto Laravel 8 e Livewire. Ao pesquisar um cep inválido está retornando este erro:

Return value of Canducci\ZipCode\ZipCode::getZipCodeInfo() must be of the type string, null returned

$addressGet = $this->zipCode($this->cep);

            if($addressGet) {
                $address = $addressGet->getArray();

                $this->address['title'] = $address['logradouro'];
                $this->address['district'] = $address['bairro'];
                $this->address['city'] = $address['localidade'];
                $this->address['uf'] = $address['uf'];
                $this->address['cep'] = $address['cep'];
            }

**Comment by fulviocanducci** [comment]
Foi adicionado o `null` nos retornos função alterado nessa nova versão https://github.com/netdragoon/zipcode/releases/tag/v3.0.5
por favor teste e me dê se agora resolveu.
